@extends('layouts.owner')
@section('title','دوره‌های آموزشگاه | شیخان')
@section('header-title','دوره‌ها')
@section('content')
<div class="space-y-6 panel-page-enter">
<div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold text-[var(--color-brand-600)]">آموزشگاه</p><h1 class="mt-2 text-2xl font-black">دوره‌ها</h1><p class="mt-2 text-sm leading-7 text-[var(--color-text-secondary)]">ساخت، قیمت‌گذاری، انتشار و بازبینی دوره‌ها با pagination.</p></div><a href="{{ route('owner.courses.create') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl bg-[var(--color-brand-600)] px-4 text-sm font-black text-white">+ ساخت دوره</a></div>
<div class="grid gap-4 sm:grid-cols-3"><div class="panel-card p-5"><span class="text-xs text-[var(--color-text-muted)]">کل دوره‌ها</span><strong class="mt-2 block text-3xl font-black">{{ $stats['total'] }}</strong></div><div class="panel-card p-5"><span class="text-xs text-[var(--color-text-muted)]">منتشرشده</span><strong class="mt-2 block text-3xl font-black">{{ $stats['published'] }}</strong></div><div class="panel-card p-5"><span class="text-xs text-[var(--color-text-muted)]">رایگان</span><strong class="mt-2 block text-3xl font-black">{{ $stats['free'] }}</strong></div></div>
<section class="panel-card overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[780px] text-right"><thead class="border-b border-[var(--color-border)] bg-[var(--color-background-soft)]"><tr><th class="px-5 py-4 text-xs font-black text-[var(--color-text-muted)]">دوره</th><th class="px-5 py-4 text-xs font-black text-[var(--color-text-muted)]">وضعیت</th><th class="px-5 py-4 text-xs font-black text-[var(--color-text-muted)]">دسترسی</th><th class="px-5 py-4 text-xs font-black text-[var(--color-text-muted)]">دانش‌آموز</th><th class="px-5 py-4 text-xs font-black text-[var(--color-text-muted)]">عملیات</th></tr></thead><tbody class="divide-y divide-[var(--color-border)]">
@forelse($courses as $course)<tr class="transition hover:bg-[var(--color-background-soft)]"><td class="px-5 py-4"><div class="font-bold">{{ $course->title }}</div><div class="mt-1 text-xs text-[var(--color-text-muted)]">{{ $course->sections_count }} بخش · {{ $course->academy?->name }}</div></td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-[11px] font-bold {{ $course->status==='published'?'bg-[var(--color-success-50)] text-[var(--color-success-700)]':'bg-[var(--color-slate-100)] text-[var(--color-text-muted)]' }}">{{ match($course->status){'published'=>'منتشرشده','archived'=>'آرشیو',default=>'پیش‌نویس'} }}</span></td><td class="px-5 py-4">@if($course->isFree())<span class="rounded-full bg-[var(--color-success-50)] px-2.5 py-1 text-[11px] font-bold text-[var(--color-success-700)]">رایگان</span>@else<div><span class="rounded-full bg-[var(--color-warning-50)] px-2.5 py-1 text-[11px] font-bold text-[var(--color-warning-700)]">پولی</span><div class="mt-1 text-xs font-bold">{{ number_format((float)$course->price,0,'.',',') }} تومان</div></div>@endif</td><td class="px-5 py-4 text-sm font-bold">{{ $course->active_students_count }}</td><td class="px-5 py-4"><div class="flex flex-wrap gap-2"><a href="{{ route('owner.courses.show',$course) }}" class="rounded-lg bg-[var(--color-brand-50)] px-3 py-2 text-[10px] font-black text-[var(--color-brand-700)]">بازبینی</a><a href="{{ route('owner.courses.edit',$course) }}" class="rounded-lg border border-[var(--color-border)] px-3 py-2 text-[10px] font-black">ویرایش</a></div></td></tr>
@empty<tr><td colspan="5" class="px-5 py-16 text-center"><div class="text-sm font-bold">هنوز دوره‌ای ساخته نشده است.</div><p class="mt-1 text-xs text-[var(--color-text-muted)]">اولین دوره را بساز و سپس محتوای آن را مدیریت کن.</p><a href="{{ route('owner.courses.create') }}" class="mt-4 inline-flex rounded-xl bg-[var(--color-brand-600)] px-4 py-3 text-xs font-black text-white">ساخت اولین دوره</a></td></tr>@endforelse
</tbody></table></div>@if($courses->hasPages())<div class="border-t border-[var(--color-border)] p-4">{{ $courses->links() }}</div>@endif</section>
</div>
@endsection