@extends('layouts.owner')
@section('title',$course->title.' | مدیریت دوره')
@section('header-title','بازبینی دوره')
@section('content')
<div class="space-y-6 panel-page-enter">
<div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold text-[var(--color-brand-600)]">بازبینی دوره</p><h1 class="mt-2 text-2xl font-black">{{ $course->title }}</h1><p class="mt-2 text-sm text-[var(--color-text-secondary)]">{{ $course->short_description?:'توضیح کوتاهی ثبت نشده است.' }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('owner.courses.edit',$course) }}" class="rounded-xl bg-[var(--color-brand-600)] px-4 py-3 text-xs font-black text-white">ویرایش دوره</a><a href="{{ route('owner.courses.index') }}" class="rounded-xl border border-[var(--color-border)] bg-white px-4 py-3 text-xs font-bold">بازگشت</a></div></div>
<section class="grid gap-3 sm:grid-cols-4">@foreach([['دانش‌آموز فعال',$course->active_students_count],['میانگین پیشرفت',$averageProgress.'٪'],['تکلیف',$course->assignments_count],['آزمون',$course->exams_count]] as [$label,$value])<article class="panel-card p-5"><span class="text-xs text-[var(--color-text-muted)]">{{ $label }}</span><strong class="mt-2 block text-2xl font-black">{{ $value }}</strong></article>@endforeach</section>
<section class="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
<div class="panel-card p-5 sm:p-7"><div class="flex items-center justify-between"><div><h2 class="text-base font-black">ساختار محتوا</h2><p class="mt-1 text-xs text-[var(--color-text-muted)]">بخش‌ها و درس‌ها.</p></div><span class="rounded-full bg-[var(--color-brand-50)] px-3 py-1.5 text-[10px] font-bold">{{ $course->sections->count() }} بخش</span></div><div class="mt-5 grid gap-3">@forelse($course->sections as $section)<article class="rounded-2xl border border-[var(--color-border)] bg-[var(--color-background-soft)] p-4"><div class="flex items-start justify-between gap-3"><div><h3 class="text-sm font-black">{{ $section->title }}</h3>@if($section->description)<p class="mt-1 text-xs leading-6 text-[var(--color-text-secondary)]">{{ $section->description }}</p>@endif</div><span class="text-[10px] text-[var(--color-text-muted)]">{{ $section->lessons->count() }} درس</span></div><div class="mt-3 grid gap-2">@forelse($section->lessons as $lesson)<div class="flex items-center justify-between rounded-xl bg-white px-3 py-2.5"><span class="text-xs font-semibold">{{ $lesson->title }}</span><span class="text-[9px] text-[var(--color-text-muted)]">{{ $lesson->status==='published'?'منتشر':'پیش‌نویس' }}</span></div>@empty<div class="text-xs text-[var(--color-text-muted)]">درسی ثبت نشده است.</div>@endforelse</div></article>@empty<div class="rounded-2xl border border-dashed border-[var(--color-border)] p-8 text-center text-sm text-[var(--color-text-muted)]">محتوای ساختاریافته‌ای وجود ندارد.</div>@endforelse</div></div>
<aside class="space-y-5"><section class="panel-card p-5"><h2 class="text-base font-black">مدرس‌ها</h2><div class="mt-4 grid gap-2">@forelse($course->teachers as $teacher)<div class="flex items-center justify-between rounded-xl bg-[var(--color-background-soft)] px-3 py-3"><span class="text-xs font-bold">{{ $teacher->name }}</span>@if($teacher->pivot->is_primary)<span class="text-[9px] font-bold text-[var(--color-brand-700)]">اصلی</span>@endif</div>@empty<div class="text-xs text-[var(--color-text-muted)]">مدرسی اختصاص داده نشده است.</div>@endforelse</div></section><section class="panel-card p-5"><h2 class="text-base font-black">وضعیت انتشار</h2><div class="mt-4 grid gap-3 text-xs"><div class="flex justify-between"><span class="text-[var(--color-text-muted)]">وضعیت</span><strong>{{ match($course->status){'published'=>'منتشرشده','archived'=>'آرشیو',default=>'پیش‌نویس'} }}</strong></div><div class="flex justify-between"><span class="text-[var(--color-text-muted)]">دسترسی</span><strong>{{ $course->isFree()?'رایگان':number_format((float)$course->price,0,'.',',').' تومان' }}</strong></div><div class="flex justify-between"><span class="text-[var(--color-text-muted)]">کلاس آنلاین</span><strong>{{ $course->live_classes_count }}</strong></div></div></section></aside>
</section>
<section class="grid gap-5 lg:grid-cols-2"><section class="panel-card p-5 sm:p-6"><div><h2 class="text-base font-black">آزمون‌ها</h2><p class="mt-1 text-xs text-[var(--color-text-muted)]">خلاصه آزمون‌های ساخته‌شده توسط مدرس.</p></div><div class="mt-4 grid gap-2">@forelse($course->exams as $exam)<div class="rounded-xl bg-[var(--color-background-soft)] p-3"><div class="flex items-center justify-between gap-3"><strong class="text-xs">{{ $exam->title }}</strong><span class="text-[9px]">{{ $exam->status==='published'?'منتشر':'پیش‌نویس' }}</span></div><div class="mt-1 text-[9px] text-[var(--color-text-muted)]">{{ $exam->teacher?->name }} · {{ $exam->questions_count }} سؤال · {{ $exam->attempts_count }} تلاش</div></div>@empty<div class="rounded-xl bg-slate-50 p-5 text-center text-xs text-slate-500">آزمونی ثبت نشده است.</div>@endforelse</div></section><section class="panel-card p-5 sm:p-6"><div><h2 class="text-base font-black">تکالیف</h2><p class="mt-1 text-xs text-[var(--color-text-muted)]">ارسال‌ها و موارد نیازمند بررسی.</p></div><div class="mt-4 grid gap-2">@forelse($course->assignments as $assignment)<div class="rounded-xl bg-[var(--color-background-soft)] p-3"><div class="flex items-center justify-between gap-3"><strong class="text-xs">{{ $assignment->title }}</strong><span class="text-[9px] font-bold">{{ $assignment->pending_submissions_count }} مورد نیازمند بررسی</span></div><div class="mt-1 text-[9px] text-[var(--color-text-muted)]">{{ $assignment->teacher?->name }} · {{ $assignment->submissions_count }} ارسال</div></div>@empty<div class="rounded-xl bg-slate-50 p-5 text-center text-xs text-slate-500">تکلیفی ثبت نشده است.</div>@endforelse</div></section></section>
</div>
@endsection