<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('orders',function(Blueprint $t){$t->id();$t->string('order_number',64)->unique();$t->foreignId('buyer_id')->constrained('users')->restrictOnDelete();$t->string('status',32)->default('pending')->index();$t->string('currency',8)->default('IRR');$t->unsignedBigInteger('subtotal')->default(0);$t->unsignedBigInteger('discount')->default(0);$t->unsignedBigInteger('total')->default(0);$t->string('billing_name')->nullable();$t->string('billing_mobile',32)->nullable();$t->boolean('legal_consent_completed')->default(false);$t->timestamp('paid_at')->nullable()->index();$t->timestamps();$t->index(['buyer_id','status']);});
  Schema::create('order_items',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->foreignId('beneficiary_id')->nullable()->constrained('users')->nullOnDelete();$t->string('product_title_snapshot');$t->unsignedBigInteger('unit_price')->default(0);$t->unsignedInteger('quantity')->default(1);$t->unsignedBigInteger('total_price')->default(0);$t->timestamps();$t->index(['order_id','product_id']);});
  Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->string('gateway',64);$t->string('authority',128)->nullable();$t->string('transaction_id',128)->nullable();$t->string('tracking_code',128)->nullable();$t->unsignedBigInteger('amount')->default(0);$t->string('currency',8)->default('IRR');$t->string('status',32)->default('pending')->index();$t->json('gateway_response')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();$t->unique(['gateway','authority']);$t->unique(['gateway','transaction_id']);$t->index(['order_id','status']);});
  Schema::create('product_entitlements',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->foreignId('order_item_id')->unique()->constrained()->restrictOnDelete();$t->string('status',32)->default('active')->index();$t->timestamp('starts_at')->nullable();$t->timestamp('expires_at')->nullable();$t->timestamp('granted_at')->nullable();$t->timestamps();$t->index(['user_id','product_id','status']);});
  Schema::create('product_downloads',function(Blueprint $t){$t->id();$t->foreignId('entitlement_id')->constrained('product_entitlements')->cascadeOnDelete();$t->foreignId('product_file_id')->constrained()->restrictOnDelete();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->timestamp('downloaded_at')->useCurrent();$t->index(['entitlement_id','product_file_id']);});
  Schema::create('protected_files',function(Blueprint $t){$t->id();$t->foreignId('product_file_id')->constrained()->cascadeOnDelete();$t->foreignId('entitlement_id')->constrained('product_entitlements')->cascadeOnDelete();$t->string('source_checksum',64)->nullable();$t->string('generated_path');$t->string('watermark_text')->nullable();$t->string('watermark_type',32)->default('text');$t->timestamp('generated_at')->nullable();$t->timestamp('expires_at')->nullable();$t->string('status',32)->default('processing')->index();$t->unsignedInteger('download_count')->default(0);$t->timestamps();$t->unique(['product_file_id','entitlement_id']);});
 }
 public function down(): void { foreach(['protected_files','product_downloads','product_entitlements','payments','order_items','orders'] as $t) Schema::dropIfExists($t); }
};