@props(['course','academies','action','method'=>'POST','routePrefix'=>'owner.courses'])
@php($isEdit=$course->exists)
@php($currentAccess=old('access_type',$course->access_type?:'paid'))
@php($currentStatus=old('status',$course->status?:'draft'))
<div x-data="{accessType:@js($currentAccess),slug:@js(old('slug',$course->slug)),title:@js(old('title',$course->title)),syncSlug(){if(@js($isEdit))return;this.slug=this.title.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}}"
     class="space-y-6">
<form method="POST" action="{{ $action }}" class="space-y-6">@csrf @if($method!=='POST')@method($method)@endif
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
<section class="panel-card p-5 sm:p-6"><div><div class="text-xs font-bold text-[var(--color-brand-600)]">اطلاعات اصلی</div><h2 class="mt-2 text-xl font-black">تعریف دوره</h2></div><div class="mt-7 grid gap-5 sm:grid-cols-2">
<label class="grid gap-1 sm:col-span-2"><span class="text-sm font-bold">عنوان دوره</span><input name="title" x-model="title" @input="syncSlug()" value="{{ old('title',$course->title) }}" required class="min-h-12 w-full rounded-xl border border-[var(--color-border)] bg-white px-4 text-sm"><x-owner.field-error field="title"/></label>
<label class="grid gap-1"><span class="text-sm font-bold">Slug</span><input name="slug" x-model="slug" value="{{ old('slug',$course->slug) }}" required dir="ltr" class="min-h-12 w-full rounded-xl border border-[var(--color-border)] bg-white px-4 text-sm"><x-owner.field-error field="slug"/></label>
<label class="grid gap-1"><span class="text-sm font-bold">آموزشگاه</span><select name="academy_id" required class="min-h-12 w-full rounded-xl border border-[var(--color-border)] bg-white px-4 text-sm">@foreach($academies as $academy)<option value="{{ $academy->id }}" @selected((string)old('academy_id',$course->academy_id)===(string)$academy->id)>{{ $academy->name }}</option>@endforeach</select><x-owner.field-error field="academy_id"/></label>
<label class="grid gap-1"><span class="text-sm font-bold">سطح</span><input name="level" value="{{ old('level',$course->level) }}" class="min-h-12 w-full rounded-xl border border-[var(--color-border)] bg-white px-4 text-sm"><x-owner.field-error field="level"/></label>
<label class="grid gap-1"><span class="text-sm font-bold">مدت دوره (دقیقه)</span><input name="duration_minutes" type="number" min="0" value="{{ old('duration_minutes',$course->duration_minutes??0) }}" class="min-h-12 w-full rounded-xl border border-[var(--color-border)] bg-white px-4 text-sm"><x-owner.field-error field="duration_minutes"/></label>
<label class="grid gap-1 sm:col-span-2"><span class="text-sm font-bold">خلاصه</span><textarea name="short_description" rows="3" class="w-full rounded-xl border border-[var(--color-border)] bg-white px-4 py-3 text-sm">{{ old('short_description',$course->short_description) }}</textarea><x-owner.field-error field="short_description"/></label>
<label class="grid gap-1 sm:col-span-2"><span class="text-sm font-bold">توضیحات کامل</span><textarea name="description" rows="8" class="w-full rounded-xl border border-[var(--color-border)] bg-white px-4 py-3 text-sm leading-7">{{ old('description',$course->description) }}</textarea><x-owner.field-error field="description"/></label>
</div></section>
<aside class="space-y-6">
<section class="panel-card p-5"><div class="text-xs font-bold text-[var(--color-brand-600)]">مدل دسترسی</div><h2 class="mt-2 text-lg font-black">رایگان یا پولی؟</h2><div class="mt-5 grid gap-3">
<label class="cursor-pointer rounded-2xl border p-4" :class="accessType==='free'?'border-emerald-300 bg-emerald-50':'border-[var(--color-border)] bg-white'"><input type="radio" name="access_type" value="free" class="sr-only" x-model="accessType"><div class="text-sm font-black">دوره رایگان</div><p class="mt-1 text-xs leading-6 text-[var(--color-text-secondary)]">بدون پرداخت.</p></label>
<label class="cursor-pointer rounded-2xl border p-4" :class="accessType==='paid'?'border-[var(--color-brand-300)] bg-[var(--color-brand-50)]':'border-[var(--color-border)] bg-white'"><input type="radio" name="access_type" value="paid" class="sr-only" x-model="accessType"><div class="text-sm font-black">دوره پولی</div><p class="mt-1 text-xs leading-6 text-[var(--color-text-secondary)]">دسترسی محافظت‌شده با پرداخت.</p></label>
</div><div x-show="accessType==='paid'" x-cloak class="mt-5"><label for="price" class="mb-1 block text-sm font-bold">قیمت دوره (تومان)</label><input id="price" name="price" type="number" min="0.01" step="1" :required="accessType==='paid'" value="{{ old('price',$course->price) }}" class="min-h-12 w-full rounded-xl border border-[var(--color-border)] bg-white px-4 text-sm"><x-owner.field-error field="price"/></div></section>
<section class="panel-card p-5"><div class="text-xs font-bold text-[var(--color-brand-600)]">انتشار</div><h2 class="mt-2 text-lg font-black">وضعیت دوره</h2><label class="mt-4 grid gap-1"><span class="text-xs font-bold">وضعیت</span><select name="status" class="min-h-12 w-full rounded-xl border border-[var(--color-border)] bg-white px-4 text-sm"><option value="draft" @selected($currentStatus==='draft')>پیش‌نویس</option><option value="published" @selected($currentStatus==='published')>منتشرشده</option><option value="archived" @selected($currentStatus==='archived')>آرشیو</option></select><x-owner.field-error field="status"/></label><label class="mt-4 grid gap-1"><span class="text-xs font-bold">تاریخ انتشار</span><input name="published_at" type="datetime-local" value="{{ old('published_at',$course->published_at?->format('Y-m-dTH:i')) }}" class="min-h-12 w-full rounded-xl border border-[var(--color-border)] bg-white px-4 text-sm"><x-owner.field-error field="published_at"/></label></section>
<button type="submit" class="inline-flex min-h-12 items-center justify-center rounded-xl bg-[var(--color-brand-600)] px-5 text-sm font-black text-white">{{ $isEdit?'ذخیره تغییرات':'ساخت دوره' }}</button><a href="{{ route($routePrefix.'.index') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl border border-[var(--color-border)] bg-white px-5 text-sm font-bold text-[var(--color-text-secondary)]">انصراف</a>
</aside></div></form>
@if($isEdit)
<section class="panel-card p-5 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div class="text-xs font-bold text-[var(--color-brand-600)]">رسانه</div><h2 class="mt-2 text-xl font-black">فایل‌های خصوصی و آموزشی</h2><p class="mt-2 text-sm leading-7 text-[var(--color-text-secondary)]">فایل‌های آموزشی private ذخیره می‌شوند.</p></div><form method="POST" action="{{ route($routePrefix.'.media.store',$course) }}" enctype="multipart/form-data" class="flex flex-col gap-2 sm:min-w-[24rem] sm:flex-row">@csrf<input type="hidden" name="collection" value="course-assets"><input type="file" name="media" required class="min-h-11 flex-1 rounded-xl border border-[var(--color-border)] bg-white px-3 py-2 text-xs" accept=".jpg,.jpeg,.png,.webp,.pdf,.mp4,.webm,.mov,.zip"><button class="min-h-11 rounded-xl bg-slate-900 px-4 text-xs font-black text-white">آپلود</button></form></div>
<div class="mt-6 grid gap-3">@forelse($course->media as $media)<div class="flex flex-col gap-3 rounded-2xl border border-[var(--color-border)] bg-[var(--color-background-soft)] p-4 sm:flex-row sm:items-center sm:justify-between"><div class="min-w-0"><div class="truncate text-sm font-bold">{{ $media->original_name }}</div><div class="mt-1 text-xs text-[var(--color-text-muted)]">{{ $media->mime_type?:'فایل' }} · {{ number_format($media->size/1024/1024,2) }} MB · Private</div></div><form method="POST" action="{{ route($routePrefix.'.media.destroy',[$course,$media]) }}">@csrf @method('DELETE')<button type="submit" data-confirm="این فایل حذف شود؟" class="rounded-xl border border-[var(--color-danger-100)] bg-[var(--color-danger-50)] px-3 py-2 text-xs font-bold text-[var(--color-danger-600)]">حذف فایل</button></form></div>@empty<div class="rounded-2xl border border-dashed border-[var(--color-border-strong)] bg-[var(--color-background-soft)] p-8 text-center"><div class="text-sm font-bold">هنوز فایلی اضافه نشده.</div><p class="mt-1 text-xs text-[var(--color-text-muted)]">ویدیو، PDF یا فایل آموزشی را اضافه کن.</p></div>@endforelse</div></section>
@endif
</div>